"""
models.py

Data models used throughout the Source Discovery Agent.

These models define the contract between all internal modules.
Business logic should NEVER exist inside this file.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional
from uuid import uuid4


# -------------------------------------------------------------------
# User Input
# -------------------------------------------------------------------

@dataclass(slots=True)
class DomainInput:
    """
    User request for discovering information sources.
    """

    domain: str
    description: Optional[str] = None

    max_sources: int = 10

    quality_threshold: float = 0.70

    search_budget: int = 5


# -------------------------------------------------------------------
# Domain Context
# -------------------------------------------------------------------

@dataclass(slots=True)
class DomainContext:
    """
    Rich understanding of the requested domain.
    Produced by DomainUnderstanding module.
    """

    domain: str

    keywords: List[str]

    synonyms: List[str]

    related_topics: List[str]

    generated_at: datetime = field(default_factory=datetime.utcnow)


# -------------------------------------------------------------------
# Search Query
# -------------------------------------------------------------------

@dataclass(slots=True)
class SearchQuery:
    """
    One search query generated by the Search Planner.
    """

    query: str

    priority: int = 1

    generated_by: str = "llm"


# -------------------------------------------------------------------
# Raw Search Result
# -------------------------------------------------------------------

@dataclass(slots=True)
class SearchResult:
    """
    Raw result returned by a search engine.

    This has NOT yet been converted into a Source.
    """

    title: str

    url: str

    snippet: str

    rank: int


# -------------------------------------------------------------------
# Final Source Object
# -------------------------------------------------------------------

@dataclass(slots=True)
class Source:
    """
    Final structured source produced by the Source Discovery Agent.
    """

    id: str = field(default_factory=lambda: str(uuid4()))

    title: str = ""

    url: str = ""

    source_type: str = "unknown"

    discovery_reason: str = ""

    page_summary: str = ""

    relevance_score: float = 0.0

    authority_score: float = 0.0

    freshness_score: float = 0.0

    final_score: float = 0.0

    confidence: float = 0.0

    discovered_at: datetime = field(default_factory=datetime.utcnow)


# -------------------------------------------------------------------
# Agent Output
# -------------------------------------------------------------------

@dataclass(slots=True)
class SourceDiscoveryResult:
    """
    Final output returned by the Source Discovery Agent.
    """

    domain: str

    sources: List[Source]

    iterations: int

    total_candidates: int

    execution_time: float